### ISSUE TITLE
Importér applikation fra klima

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#2]
```[tasklist]
### Tasks
- [x] Udstil nyt endpoint
- [x] Ændr data target i OS2
- [ ] Test data push
```

**Comment by st-randers** [comment]
Applikation er flyttet til eget repository og er pt. ved at blive deployed /testet.
