### ISSUE TITLE
Upload af sensordata til EnergyKey

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#26]
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/vis-os2iot-data/issues/27
- [x] Opsætning af dataintegration i EnergyKey
- [x] Automatisk overførsel af CSV-filer til FTP
```
