### ISSUE TITLE
Opsætning af brugergrænseflade til målerregistrering

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/vis-os2iot-data#30]
```[tasklist]
### Tasks
- [x] RED: Opsæt OS2 flow med ny metadata tabel
- [x] RED: Inner join med seneste data + målepunkter på device/get
- [x] VUE: EditSensor.vue
- [x] VUE: EditLocation.vue
- [x] VUE: EditMeasurementPoint.vue
```

**Comment by st-randers** [comment]
Eksporteret til separat projekt.
